# Generated by Django 5.0.6 on 2024-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_system', '0002_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
