# Generated by Django 5.0.6 on 2024-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_system', '0003_alter_hashtag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='post_system.hashtag'),
        ),
    ]
