# Generated by Django 5.0.6 on 2024-07-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_system', '0005_remove_post_hashtags_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='post_system.hashtag'),
        ),
    ]
