# Generated by Django 5.0.6 on 2024-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_system', '0006_remove_post_hashtags_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
