# Generated by Django 5.0.6 on 2024-08-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0005_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
    ]
