# Generated by Django 5.0.6 on 2024-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='html',
            field=models.TextField(default=None, null=True),
        ),
    ]
