# Generated by Django 5.0.6 on 2024-07-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0002_notification_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date', 'is_seen']},
        ),
    ]
