# Generated by Django 4.1.13 on 2024-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/default_avatar.png', upload_to='avatars'),
        ),
    ]
