# Generated by Django 5.0.6 on 2024-07-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_profile_is_private_followrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='confirmed',
        ),
    ]
